services:
  # Наше приложение
  app:
    user: "1000:1000"
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: dev
    ports:
      - "${APP_PORT:-80}:8000"      # Можно настроить порт в .env (по умолчанию 80)
      - "${VITE_PORT:-5173}:5173"
      - "${FORWARD_XDEBUG_PORT:-2019}:2019"
    volumes:
      - .:/app
    environment:
      # Переменные Laravel берем из окружения
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}

      # База данных
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE} # Берет из .env
      DB_USERNAME: ${DB_USERNAME} # Берет из .env
      DB_PASSWORD: ${DB_PASSWORD} # Берет из .env
      
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null} # Если пароля нет, будет null
      
      # Vite
      VITE_HMR_HOST: localhost
      
      # FrankenPHP
      FRANKENPHP_BINARY: /usr/local/bin/frankenphp
      OCTANE_SERVER: frankenphp
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
      build:
        context: .
        dockerfile: docker/Dockerfile
        target: dev
      volumes:
        - .:/app
      environment:
        # Переменные такие же как в app
        APP_ENV: local
        QUEUE_CONNECTION: rabbitmq
        DB_HOST: db
        RABBITMQ_HOST: rabbitmq
      # ГЛАВНОЕ: Меняем команду запуска. Вместо веб-сервера запускаем обработчик очереди
      command: php artisan queue:work --tries=3 --timeout=90
      depends_on:
        - rabbitmq
        - db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "${FORWARD_RABBITMQ_PORT:-5672}:5672"   # Порт для передачи данных (AMQP)
      - "${FORWARD_RABBITMQ_WEB_PORT:-15672}:15672" # Порт для веб-админки
    volumes:
      - rabbit-data:/var/lib/rabbitmq # Сохраняем данные очередей
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # База данных
  db:
    image: postgres:16-alpine
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432" # Порт наружу тоже можно менять
    environment:
      POSTGRES_DB: ${DB_DATABASE}     # Postgres создаст базу с этим именем
      POSTGRES_USER: ${DB_USERNAME}   # И этим юзером
      POSTGRES_PASSWORD: ${DB_PASSWORD} # И этим паролем
    volumes:
      - pg-data:/var/lib/postgresql/data

  # Кэш
  redis:
    image: redis:alpine
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    # Если нужен пароль для Redis, раскомментируй:
    # command: redis-server --requirepass ${REDIS_PASSWORD}

  # Почта
  mailpit:
    image: axllent/mailpit
    ports:
      - "${FORWARD_MAIL_PORT:-1025}:1025"
      - "${FORWARD_MAIL_WEB_PORT:-8025}:8025"

  s3:
    image: minio/minio
    ports:
      - "${FORWARD_S3_PORT:-9000}:9000" # API
      - "${FORWARD_S3_CONSOLE_PORT:-9001}:9001" # Консоль управления
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    volumes:
      - s3-data:/data
    command: server /data --console-address ":9001"

  # База данных для логов http://loki:3100
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "${FORWARD_LOKI_PORT:-3100}:3100"
    command: -config.file=/etc/loki/local-config.yaml


  # Агент, который читает логи Docker и шлет в Loki
  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Чтобы видеть логи других контейнеров
      - ./docker/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  # Интерфейс
  grafana:
    image: grafana/grafana:latest
    ports:
      - "${FORWARD_GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

  
  k6:
    image: grafana/k6
    volumes:
      - ./docker/k6:/scripts
    command: run /scripts/test.js

    
volumes:
  pg-data:
  redis-data:
  s3-data:
  rabbit-data: